name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          extra-substituters = https://hydra.iohk.io
          extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
    - uses: cachix/cachix-action@v10
      with:
        name: scarf
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: cachix,iohk,nix-community
    - run: nix build
    - run: nix develop --build
